# Generated by Django 5.1.7 on 2025-03-31 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_password_reset_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='password_reset_required',
            new_name='password_must_be_reset',
        ),
    ]
